### ISSUE TITLE
Error related to model scout 

### ISSUE THREAD

**Issue by waqaszaidi** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#10]
I am using python3.9 with pytorch1.8 and ros noetic installed. Whenever i try to open main.py in SAC folder, it opens all the windows but no simulation and this error come 

 [ERROR] [1719499745.569493391, 1460.034000000]: Updating ModelState: model [scout] does not exist

**Comment by OscarHuangWind** [comment]
Have you gone through all the steps in the ReadMe? Especially this step:
"Copy all the files under models folder to your default gazebo models folder."
