### ISSUE TITLE
No movement

### ISSUE THREAD

**Issue by alyssaserrano** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#12]
Do you have any insight on these errors that I am experiencing? I followed the user guidance and also commented out lines 429-432 as instructed, and these errors are still present. All the windows pop up normally and show the robot as well, the only problem is the errors presented in the terminal and the robot not moving.
![Screenshot from 2024-07-14 14-40-52](https://github.com/user-attachments/assets/a97b3b46-0744-49fa-88e3-f258c8bd43b1)
![Screenshot from 2024-07-14 14-41-04](https://github.com/user-attachments/assets/5f00771c-c7b8-4210-83ad-c9eef5b7a728)

**Comment by zyy20010609** [comment]
I have same question, the robot not moving.
Look forward to your reply
![2024-07-17 13-43-07 的屏幕截图](https://github.com/user-attachments/assets/fa145f21-b001-4590-8885-c8be02f6bfc5)

**Comment by zyy20010609** [comment]
![2024-07-15 22-11-59 的屏幕截图](https://github.com/user-attachments/assets/586b0b24-b35f-4fb8-8a15-41c78d701081)

**Comment by alyssaserrano** [comment]
From looking more into the issue, is there a problem with advertising the topic for the fisheye camera?

**Comment by OscarHuangWind** [comment]
> From looking more into the issue, is there a problem with advertising the topic for the fisheye camera?

Hmm.. It seems issue of CV2 and rgb from fisheye camera. Is the version of the CV2 same as the one in environment file in this repo?

**Comment by OscarHuangWind** [comment]
@zyy20010609 Hi, I cannot see the figures you attached above, maybe it is better to post your issue as a new one and provide the screenshot.

**Comment by alyssaserrano** [comment]
The opencv-python version I have 4.10.0.84, what version did you have?

**Comment by OscarHuangWind** [comment]
I was using 4.2.0.34 during this work. You may want to downgrade your opencv and give a try

**Comment by alyssaserrano** [comment]
Ok I'll give that a try, also what version of Gazebo did you run this on?

**Comment by OscarHuangWind** [comment]
Should be Gazebo 11, as far as I remember

**Comment by zyy20010609** [comment]
> Should be Gazebo 11, as far as I remember

yes, Gazebo multi-robot simulator, version 11.11.0

**Comment by alyssaserrano** [comment]
@zyy20010609 do you mind sharing all the dependency package versions you installed on conda?

**Comment by alyssaserrano** [comment]
Update I figured out the problem thanks to the [discussion](https://github.com/ros-perception/vision_opencv/issues/509). I just re-linked the library.
