### ISSUE TITLE
Testing a trained model

### ISSUE THREAD

**Issue by alyssaserrano** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#13]
Firstly, I appreciate the help you provided on a previous issue I was facing. So I have trained my model, I wanted to know how I can load the trained model instead of training a new one. Hope to hear from you soon, thank you.

**Comment by OscarHuangWind** [comment]
Thank you and sorry for the late reply.

The fastest method is editing the main.py file with minor revisions.
1. Load the model: 
` 
ego.load_actor(file_name, directory="./final_models") # path to the model saved
`
`
ego.policy.eval()
`

2. Call the evaluate function in main.py file.
`
avg_reward = evaluate(ego, EVAL_EPOCH, ep_real)
`

However, I would recommend creating a new evaluation.py file and D.I.Y. evaluation code as your demand.

**Comment by alyssaserrano** [comment]
Ok thanks for the advice!

**Comment by alyssaserrano** [comment]
Hi there, I tried your advice of how to load the model and call the evaluation function in main.py file. However a bunch of errors come up. I used the pretrained (lines 286-290) config to trigger my pretrained model to be evaluated. Here is both the errors and code. I appreciate the help!
![Screenshot from 2024-10-08 11-07-42](https://github.com/user-attachments/assets/9dc9f177-4701-4b35-b6f3-46d2c899f0ec)
![Screenshot from 2024-10-08 11-06-09](https://github.com/user-attachments/assets/ff147a79-71a8-4a7b-81c9-a66428140581)

**Comment by OscarHuangWind** [comment]
From the error it is clear that it is the issue of dimension mismatching.
This issue may be caused by various reasons, such as the model parameter mismatching, the input mismatching and so on.
You can locally debug based on the error indication.
