### ISSUE TITLE
How to Store Expert Data Before Training in SAC Algorithm

### ISSUE THREAD

**Issue by zahra370** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#14]
I’m having trouble figuring out how to first store expert data into the replay buffer and then start the training process in the SAC algorithm. would you please guide me on the correct sequence for storing expert data and initiating the training phase?

**Comment by OscarHuangWind** [comment]
Below I list the steps that I would recommend:

1. Collect the expert data: 
`python3 demonstration.py` 
(https://github.com/OscarHuangWind/DRL-Transformer-SimtoReal-Navigation/blob/master/catkin_ws/src/gtrl/scripts/DIL/demonstration.py)

2. Load the pre-buffer from expert data: set the "PRE_BUFFER" parameter as True in config.yaml and run
`python3 main.py`

4. Enable the human-in-the-loop guidance: set the "HUMAN_INTERVENTION " parameter as True in config.yaml and run
`python3 main.py`
