### ISSUE TITLE
how many episode should I have?

### ISSUE THREAD

**Issue by leonNg369** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#15]
大佬您好, 我想請教
human-in-the-loop = false 
同
human-in-the-loop = true
大概需要多少episode 才能做到demo 的效果

因為human-in-the-loop = false的情況下並沒有出現避障的效果

**Comment by OscarHuangWind** [comment]
感谢关注
理论上默认参数应该是直接能收敛的，main.py里面用的是哪个模型？config文件里的参数有改动过吗

**Comment by leonNg369** [comment]
main.py 用的是GoT-SAC, config 只改了MAX_EPISODES -> (500, 1000, 10000)  在human-in-the-loop = false的情況, 沒有嘗試 human-in-the-loop = true.

**Comment by OscarHuangWind** [comment]
我这边本地跑的在同样的设置和seed都可以收敛，可以看一下训练好的reward曲线长啥样，他是上升了振荡还是完全发散了

**Comment by leonNg369** [comment]
![image](https://github.com/user-attachments/assets/57d7eef5-e5a9-4dd9-90b7-da5597774df9)
唔好意思,只有10000次的,忘了改名子
會不會是library version不同,因為我是在docker上跑,能否給一下library version的嗎? 謝謝

**Comment by OscarHuangWind** [comment]
这个属于是陷入sub-optimal了。
我建议的话先试一下下面两种方案：
1. 改seed跑一次
2. 把模型换成SAC，看看是不是有同样的问题

**Comment by leonNg369** [comment]
不好意思,还是没有达到预期效果
SAC:
![reward_seed555_drl](https://github.com/user-attachments/assets/2f97b43c-a2b2-4725-be61-76e981e0733f)
Got-SAC(电脑卡了只跑了一半)
![reward_seed555_gtrl](https://github.com/user-attachments/assets/8cdf232e-319d-4665-82db-2dd002df6ed8)
有什么建议吗?
請問gazebo fps 會有影響嗎? 我fps 只有2...

**Comment by OscarHuangWind** [comment]
fps会不会影响我没有试过，每次都是同一台主机上训练的。
第二个gtrl的奖励函数曲线有点怪，看起来是完全没有收敛。有看到过具体车的行为吗？他是一直撞障碍物还是杵在原地不动？

我提供一个思路，你可以试试：
把 catkin_ws/src/gtrl/scripts/Environments/env_lab.py 中 85, 86行的self.upper和self.lower设置小一点，一开始让目标点离本车生成近一些，看看算法收不收敛

**Comment by leonNg369** [comment]
我把修改了一部份程式,令它能在ROS2上跑。fps能上升到60，仿真順𣈱很多，training時間縮短了。
但是成功率最多只有60％左右，整體都是朝目标前进，有時轉向會發生碰撞和前方有障碍物没有回避。

result:
SAC
![Screenshot from 2024-10-28 17-13-13](https://github.com/user-attachments/assets/670f7650-0a3c-4872-a4c4-c87b4723cd7b)

GoT-SAC
![Screenshot from 2024-10-28 17-08-30](https://github.com/user-attachments/assets/5c2f8995-ffe2-44f4-9c71-b01acd4903e9)

ROS2 修改
使用线程来不断更新相机和激光数据
![image](https://github.com/user-attachments/assets/0375893d-087a-4c83-961f-25ad052eb9d4)
提取數據
![image](https://github.com/user-attachments/assets/13b65869-42de-4e8f-9664-3d8a2ccc74c6)
車的模式参考了
https://github.com/agilexrobotics/ugv_gazebo_sim/tree/humble/scout

**Comment by OscarHuangWind** [comment]
有些目标点确实很难学到，但是最后收敛后总体成功率应该得是60%以上，而且Reward应该在100上下。
Ros2的话我没有试过，但是能运行应该是至少pipeline跑通了，不确定的是传感器的输入ROS1和ROS2中不知道是不是一致的
