### ISSUE TITLE
high negative reward 

### ISSUE THREAD

**Issue by Seher-789** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#17]
reward is highly negative what seed value should i set? should i set the lower seed value or higher? i tried with 313,42,515 but the reward is highly negative . let me know please 
![Screenshot from 2024-10-16 00-15-26](https://github.com/user-attachments/assets/874c7f9e-a186-40b5-82f6-10e6614b6754)
![Screenshot from 2024-10-16 00-25-24](https://github.com/user-attachments/assets/c270e681-bdb1-4d6b-b090-1beaa51958b9)

**Comment by OscarHuangWind** [comment]
Hi, the reward will progressively increase as training proceeds. In my local setup, the reward reaches between 100 to 150 after approximately 300 episodes. The seed setting isn't a primary factor for convergence. However, for reference, I've tried various seed values such as 0, 1, 25, 42, 525, and 3407 (StackOverflow mentioned that 3407 is a "magic" seed).

If you want to quickly check the convergence performance of GTRL/SAC, you can set the self.upper and self.lower parameters in catkin_ws/src/gtrl/scripts/Environments/env_lab.py (lines 85 and 86) to lower values (e.g. 6 or 8). This will ensure that the randomly generated destination is closer to the ego vehicle.
