### ISSUE TITLE
Attention Flow Visualization

### ISSUE THREAD

**Issue by n-shintaro** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#18]
Hello,

I’m interested in your paper, "Goal-Guided Transformer-Enabled Reinforcement Learning for Efficient Autonomous Navigation," and I’m currently working with your code.

In the paper, you visualized the attention flow map, but I couldn’t find the corresponding code in the repository.

Could you provide the code for visualizing it, or let me know how it can be done if you used a different library?

I look forward to hearing from you. Thank you!

**Comment by OscarHuangWind** [comment]
Thank you for your attention. 
Below is the open-sourced repo I utilized and modified for my attention visualization. 
[luo3300612/Visualizer](https://github.com/luo3300612/Visualizer)

By the way, there are many open-source repositories on GitHub for attention visualization. The one I used has a potential issue: the README is in Chinese. If you can't read Chinese, you can try searching "ViT attention visualization" on GitHub and choose any other repository that suits you.

**Comment by n-shintaro** [comment]
Thanks for the advice!

**Comment by n-shintaro** [comment]
I have another question. In your paper, you describe the input image as an RGB image, but in your code with the default parameter(data_obs_fish), it seems that a monochrome image is used. Which one is correct? I would appreciate your confirmation.

**Comment by OscarHuangWind** [comment]
Hi, i tried all RGB, mono, and depth and found that both RGB and mono can converge.
As far as I remember, the mono image is also not pure gray scale figure, you can use plt.imshow to confirm it.
