### ISSUE TITLE
Convergence curve comparison

### ISSUE THREAD

**Issue by asliyigit2** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#19]
Thank you for your work.

I reviewed your codes and trained them for 500 episodes.

![44_grafik (copy)](https://github.com/user-attachments/assets/87aca8b9-4655-4428-bf44-ba921444456c)

However, when I examined the code, I could not find how you drew the Convergence curve comparison graph in Figure 5 in the article.

I share the chart below. I would like your guidance and help in drawing the graph given in Figure 5.

![Figure5](https://github.com/user-attachments/assets/f35871ad-7aa0-42cf-b332-545182496727)

**Comment by OscarHuangWind** [comment]
Thank you for your attention.

Figure 5 plots the mean and variance of the moving average reward, which means if you got five moving average rewards (the orange curve in your training reward plot) with five random seeds, you can obtain mean and variance as Fig. 5 shows.

**Comment by asliyigit2** [comment]
Thank you for your returns. 

Can you share the source codes?

**Comment by OscarHuangWind** [comment]
Sorry for late reply.

I just checked out my workspace and unfortunately, I could not find the source code of plotting I utilized for this work, since this is the one I developed around two years ago and has been already cleared from local PC after publishing the main code in Github.
