### ISSUE TITLE
Sorry to bother you

### ISSUE THREAD

**Issue by Starfishzzz** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#20]
The issue is due to my negligence. Sorry to bother you

**Comment by OscarHuangWind** [comment]
No worries and feel free to contact me if you have further questions.

**Comment by Starfishzzz** [comment]
> No worries and feel free to contact me if you have further questions.

OKOK. Thanks for your time sincerely.

**Comment by Starfishzzz** [comment]
Hello! I am trying to load the model trained through 'attention_imitation.py', and I get the file whose type is '.pth'.
![2025-01-01 11-11-49屏幕截图](https://github.com/user-attachments/assets/9c839c4d-6d04-4800-95ed-aa4aa70b8e4a)
Then, I copy 'gtrl_actor.pth' to the directiory, '/gtrl/scripts/SAC/final_models', and have modified the 'config.yaml'. Finally, an error arises.
![2025-01-01 11-22-11屏幕截图](https://github.com/user-attachments/assets/83b892b5-e89b-4280-8529-8b025e1a261d)
So, I have to ask for your help. Could you tell me which step went wrong or how to load the model trained through 'attention_imitation.py'?

**Comment by Starfishzzz** [comment]
I have found the reason for the error. I wrongly assigned a bool value to the ego(SAC).block, so the keys related to the transformer were lost. I'm very sorry to disturb you.
