### ISSUE TITLE
Encountered issues during training

### ISSUE THREAD

**Issue by chenyang126** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#5]
![2024-01-26 17-46-30 的屏幕截图](https://github.com/OscarHuangWind/DRL-Transformer-SimtoReal-Navigation/assets/125660450/b836bfab-a74e-42c6-b917-0a3a2db327e6)

When I started training, I got stuck on this interface and couldn't continue training. What is the reason for this?
I hope to receive your help！！！

**Comment by OscarHuangWind** [comment]
Hi, I guess the dynamic plots block the training process. There are two suggestions to fix this issue.

1. Comment out from line 429 to 432 in main.py file (necessary) and use tensorboard or wandb to visualize the real time plots (optional).
or
2. Run the program with Spyder IDE.

**Comment by chenyang126** [comment]
Thanks for help！I run the program with Spyder IDE(version=4.2.2), then the training process image can be dynamically updated, but the number of training rounds cannot be displayed in the terminal. 

![2024-01-26 23-39-58 的屏幕截图](https://github.com/OscarHuangWind/DRL-Transformer-SimtoReal-Navigation/assets/125660450/96673596-901c-4dc8-babc-e2ee65dce563)

When i comment out from line 429 to 432 in main.py file, i can see the following info in terminal.

![2024-01-26 23-45-47 的屏幕截图](https://github.com/OscarHuangWind/DRL-Transformer-SimtoReal-Navigation/assets/125660450/2671cbac-30a2-4b47-ae25-cd6b6197f1e8)

Can't these two types of information be displayed simultaneously?

**Comment by OscarHuangWind** [comment]
Well, I saw the process bar is already displayed at the last line of the Spyder Console, I didn't get the state "the number of training rounds cannot be displayed in the terminal", can you provide more details? 

As for the spawn model error, try to set the parameter called "sim_time" to 0 in RRC1.world file.

If you'd like to run the program in the terminal, then the best way to visualize the dynamic images is to utilize the third party dependencies. In this case, as I mentioned above, the Tensorboard or Wandb will help. You may check the manual through following links:

1. Tensorboard: https://pytorch.org/docs/stable/tensorboard.html
2. Wandb: https://github.com/wandb/wandb

**Comment by chenyang126** [comment]
Thank you very much for your answer!
