### ISSUE TITLE
issue about ROS path [0]

### ISSUE THREAD

**Issue by Hyland236** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#6]
Thank you for your work. I am a beginner in ROS. When I followed the steps and went to Python main. py, I encountered the following error. I hope you can help me.

```
Resource not found: gtrl
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/opt/ros/noetic/share
The traceback for the exception was written to the log file
```

**Comment by OscarHuangWind** [comment]
Please try the following two steps and let me know your response. Also, make sure that the ROS version is noetic on your PC.

1. Have you successfully compiled the gtrl package? 
  - cd ~/$your workspace/DRL-Transformer-SimtoReal-Navigation/catkin_ws
  - catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3

2. If yes, make sure source your workspace before running main.py
  - cd ~/$your workspace/DRL-Transformer-SimtoReal-Navigation/catkin_ws
  - source devel/setup.bash

**Comment by Damon624** [comment]
Thank you for your reply. 
I have already executed these two steps before running **main.py**. 
I think the problem should be with the **roslaunch**. When I run _**'roslaunch+absolute path/main.launch**'_ separately, it will also report the same error.
I can only open Gazebo and rviz by running the _**'roslaunch package main. launch'**_ in the workspace.

**Comment by Damon624** [comment]
thank u, I successfully opened it without relying on vscode. 
But the error occurs:
```
[ERROR] [1709013990.204467]: bad callback: <bound method GazeboEnv.image_fish_callback of <Environments.env_lab.GazeboEnv object at 0x7fbb0c088950>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/hu/dong/04ros/DRL-Transformer-SimtoReal-Navigation/catkin_ws/src/gtrl/scripts/Environments/env_lab.py", line 197, in image_fish_callback
    image = self.br.imgmsg_to_cv2(rgb_data, "mono8")
  File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 163, in imgmsg_to_cv2
    dtype, n_channels = self.encoding_to_dtype_with_channels(img_msg.encoding)
  File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 99, in encoding_to_dtype_with_channels
    return self.cvtype2_to_dtype_with_channels(self.encoding_to_cvtype2(encoding))
  File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 91, in encoding_to_cvtype2
    from cv_bridge.boost.cv_bridge_boost import getCvType
ImportError: /lib/libgdal.so.26: undefined symbol: TIFFReadRGBATileExt, version LIBTIFF_4.0

```
can u help me, thanks.

**Comment by DMU-XMU** [comment]
> Thank you for your work. I am a beginner in ROS. When I followed the steps and went to Python main. py, I encountered the following error. I hope you can help me.
> 
> ```
> Resource not found: gtrl
> ROS path [0]=/opt/ros/noetic/share/ros
> ROS path [1]=/opt/ros/noetic/share
> The traceback for the exception was written to the log file
> ```

Hi, I have the same problem. How did you solve it? Although I am not using vscode, the issue still occurs, can you share some details about the resolution? Thanks!

**Comment by JinchuanMa** [comment]
> > Thank you for your work. I am a beginner in ROS. When I followed the steps and went to Python main. py, I encountered the following error. I hope you can help me.
> > ```
> > Resource not found: gtrl
> > ROS path [0]=/opt/ros/noetic/share/ros
> > ROS path [1]=/opt/ros/noetic/share
> > The traceback for the exception was written to the log file
> > ```
> 
> Hi, I have the same problem. How did you solve it? Although I am not using vscode, the issue still occurs, can you share some details about the resolution? Thanks!

I had the same problem at first, but following the author's approach, I managed to solve it.

- Activate the gtrl environment in the terminal
- Compiled the gtrl package
- Source your workspace
- Run main.py in terminal
