### ISSUE TITLE
Code Inquiry: Gini Coefficient, Shannon-Wiener, Heatmap, and Model Testing

### ISSUE THREAD

**Issue by zahra370** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#7]
It's great that you shared your work. Can you tell me in which part of the code you calculated Gini coefficient and Shannon-Wiener, and where the heatmap was generated? I couldn't find its plot, and once the model is trained, how do you test it?

**Comment by OscarHuangWind** [comment]
Thank you for your comment.
The current version of the repo only contains the code of main technical contribution of our work.

Regarding your comment:

1. Attention Evaluation: I utilized and modified this repo(https://github.com/luo3300612/Visualizer) for my attention visualization and evaluation (Gini and SW). 

2. Model Evaluation: After finishing the training process, you will get the saved model in ./final_models folder. You can load and evaluate it in the same environment or new environment by employing different XXX.world in "catkin_ws/src/gtrl/launch/empty_world.launch" file.
