### ISSUE TITLE
An unknown PID process bug

### ISSUE THREAD

**Issue by DMU-XMU** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#8]
Hi, I always have the following problems, can you help me?

I followed your process correctly, but it seems that one process keeps failing and restarting.
You can view the following two images:
![屏幕截图 2024-06-20 121408](https://github.com/OscarHuangWind/DRL-Transformer-SimtoReal-Navigation/assets/43468643/315371c8-ec6e-48af-af7b-07c0149650ca)
[roslaunch][ERROR] 2024-06-20 11:57:45,853: [gazebo-1] process has died [pid 86943, exit code 255, cmd /opt/ros/noetic/lib/gazebo_ros/gzserver -e ode /home/dmu00/LDY/DRL-Transformer-SimtoReal-Navigation/catkin_ws/src/gtrl/world/RRC1.world __name:=gazebo __log:=/home/dmu00/.ros/log/34993bdc-2eb9-11ef-88e2-97046b9aa4bc/gazebo-1.log].

And the last log info is: 
1. [INFO] [1718855857.855445, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
2. 0.000000000 INFO /spawn_scout_model [gazebo_interface.py:27(spawn_urdf_model_client)] [topics: /rosout, /clock] Waiting for service /gazebo/spawn_urdf_model

**Comment by bengbeng833** [comment]
how to solve it,waiting for your answer,please
