### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by benllame** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#9]
Dear Team,

Excellent work! I would like to reproduce your project, but my computer runs Ubuntu 22.04, and ROS Noetic is not available for this version. I have attempted to create a Docker container without success. Would it be possible for you to provide a Dockerfile? Alternatively, is there another way to reproduce your work on this version?

I look forward to your response.

Thank you in advance.

**Comment by OscarHuangWind** [comment]
Thank you for your acknowledgement. 
Unfortunately, I am not quite familiar with Docker and do not have computer with Ubuntu 22.04.

Maybe you can try to run the code first and if try to adjust the dependencies' version to the Ubuntu 22.04 if there show any errors.

Alternatively, you can install Ubuntu 20.04 and corresponding version of ROS in Docker and run the code, think this is the better way to let the pipeline work.

**Comment by benllame** [comment]
Thanks to this repository: 'https://github.com/lesaf92/ros_noetic_ubuntu22', I was able to run and install everything on Ubuntu 22.04.
